include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # General
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    
    # Documentation
    public_member_api_docs: false
    
    # Style
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    
    # Analysis
    avoid_dynamic_calls: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"