name: app_notificaciones_ordenes
description: "Flutter production management app for order notifications and operations"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17

  # Routing
  go_router: ^16.2.1

  # HTTP & JSON
  dio: ^5.6.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

  # Barcode Scanner
  mobile_scanner: ^7.0.1

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0

  # Build tools
  build_runner: ^2.4.12
  riverpod_generator: ^3.0.0-dev.17

flutter:
  uses-material-design: true

  # Enable generation of localized Strings
  generate: true

  # Assets
  # assets:
  #   - images/

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic